

DROP VIEW IF EXISTS "INFORMATION_MARTS"."DIM_CUSTOMERS";
CREATE  VIEW "INFORMATION_MARTS"."DIM_CUSTOMERS"  AS 
	SELECT 
		  UPPER(SHA1_HEX(  UPPER(REPLACE(COALESCE(TRIM( "HUB_SRC"."CUSTOMERS_HKEY"),'~'),'\#','\\' || '\#'))|| '\#' || UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("PIT_SRC"."SNAPSHOT_DATE",
			 'DD/MM/YYYY HH24:MI:SS')),'~'),'\#','\\' || '\#'))|| '\#'  )) AS "DIM_CUSTOMERS_HKEY"
		, "HUB_SRC"."CUSTOMERS_HKEY" AS "CUSTOMERS_HKEY"
		, "HUB_SRC"."PERSON_ID_BK" AS "PERSON_ID_BK"
		, "PIT_SRC"."SNAPSHOT_DATE" AS "LOAD_DATE"
		, "PIT_SRC"."END_SNAPSHOT_DATE" AS "END_LOAD_TIMESTAMP"
		, "SAT_SRC1"."FIRST_PURCHASE" AS "FIRST_PURCHASE_SAT_SLS_CUSTOMERS_GDPR"
		, "SAT_SRC1"."IS_ACTIVE" AS "IS_ACTIVE_SAT_SLS_CUSTOMERS_GDPR"
		, "SAT_SRC1"."GENDER" AS "GENDER"
		, "SAT_SRC1"."BIRTHDATE" AS "BIRTHDATE"
		, "SAT_SRC1"."LASTNAME" AS "LASTNAME"
		, "SAT_SRC1"."FIRSTNAME" AS "FIRSTNAME"
		, "SAT_SRC2"."ADDITIONAL_INFO" AS "ADDITIONAL_INFO"
		, "SAT_SRC2"."SEND_COMMERCIAL_MESSAGES" AS "SEND_COMMERCIAL_MESSAGES"
		, "SAT_SRC3"."KNOWN_CUSTOMER" AS "KNOWN_CUSTOMER"
		, "SAT_SRC3"."CUSTOMER_MEMBER_CARD_NO" AS "CUSTOMER_MEMBER_CARD_NO"
	FROM "BUSINESS_VAULT"."PIT_CUSTOMERS" "PIT_SRC"
	INNER JOIN "VS_DEMO_DV_SNW_FL"."HUB_CUSTOMERS" "HUB_SRC" ON  "PIT_SRC"."CUSTOMERS_HKEY" = "HUB_SRC"."CUSTOMERS_HKEY"
	INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_CUSTOMERS_GDPR" "SAT_SRC1" ON  "PIT_SRC"."SAT_CUSTOMERS_HKEY_SAT_SLS_CUSTOMERS_GDPR" = "SAT_SRC1"."CUSTOMERS_HKEY" AND "PIT_SRC"."LOAD_DATE_SAT_SLS_CUSTOMERS_GDPR" =
		 "SAT_SRC1"."LOAD_DATE"
	INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_CUSTOMERS_GENERAL" "SAT_SRC2" ON  "PIT_SRC"."SAT_CUSTOMERS_HKEY_SAT_SLS_CUSTOMERS_GENERAL" = "SAT_SRC2"."CUSTOMERS_HKEY" AND "PIT_SRC"."LOAD_DATE_SAT_SLS_CUSTOMERS_GENERAL" =
		 "SAT_SRC2"."LOAD_DATE"
	INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_VST_CUSTOMERS" "SAT_SRC3" ON  "PIT_SRC"."SAT_CUSTOMERS_HKEY_SAT_VST_CUSTOMERS" = "SAT_SRC3"."CUSTOMERS_HKEY" AND "PIT_SRC"."LOAD_DATE_SAT_VST_CUSTOMERS" =
		 "SAT_SRC3"."LOAD_DATE"
	;
