
USE CATALOG healthcare; 

drop table  `HEALTHCARE_BV`.`CPIT_PATIENT`;

CREATE    TABLE `HEALTHCARE_BV`.`CPIT_PATIENT`
(
		 `PIT_HKEY` STRING
		,`PATIENT_HKEY` STRING
		,`SNAPSHOT_DATE` TIMESTAMP
		,`END_SNAPSHOT_DATE` TIMESTAMP
		,`SAT_PATIENT_HKEY_SAT_HLTH_PATIENT_PATIENT_GDPR` STRING
		,`SAT_PATIENT_HKEY_SAT_HLTH_PATIENT_PATIENT_INFO` STRING
		,`SAT_PATIENT_HKEY_CALC_SAT_HLTH_PATIENT_PATIENT_GDPR` STRING
		,`SAT_PATIENT_HKEY_CALC_SAT_HLTH_PATIENT_PATIENT_INFO` STRING
		,`LOAD_DATE_SAT_HLTH_PATIENT_PATIENT_GDPR` TIMESTAMP
		,`LOAD_DATE_SAT_HLTH_PATIENT_PATIENT_INFO` TIMESTAMP
		,`LOAD_DATE_CALC_SAT_HLTH_PATIENT_PATIENT_GDPR` TIMESTAMP
		,`LOAD_DATE_CALC_SAT_HLTH_PATIENT_PATIENT_INFO` TIMESTAMP
) 
;



USE CATALOG healthcare; 
-- POINT_IN_TIME

	INSERT INTO `HEALTHCARE_BV`.`CPIT_PATIENT`(
		 `PIT_HKEY`
		,`PATIENT_HKEY`
		,`SNAPSHOT_DATE`
		,`END_SNAPSHOT_DATE`
		,`SAT_PATIENT_HKEY_SAT_HLTH_PATIENT_PATIENT_GDPR`
		,`SAT_PATIENT_HKEY_SAT_HLTH_PATIENT_PATIENT_INFO`
		,`SAT_PATIENT_HKEY_CALC_SAT_HLTH_PATIENT_PATIENT_GDPR`
		,`SAT_PATIENT_HKEY_CALC_SAT_HLTH_PATIENT_PATIENT_INFO`
		,`LOAD_DATE_SAT_HLTH_PATIENT_PATIENT_GDPR`
		,`LOAD_DATE_SAT_HLTH_PATIENT_PATIENT_INFO`
		,`LOAD_DATE_CALC_SAT_HLTH_PATIENT_PATIENT_GDPR`
		,`LOAD_DATE_CALC_SAT_HLTH_PATIENT_PATIENT_INFO`
	)
	SELECT 
		  UPPER(sha1( `HUB_SRC`.`PATIENT_HKEY` || '#' || DATE_FORMAT(`SSDV_TGT`.`SNAPSHOT_DATE`, 
			'dd/MM/yyyy HH:mm:ss.SSSSSS') )) AS `PIT_HKEY`
		, `HUB_SRC`.`PATIENT_HKEY` AS `PATIENT_HKEY`
		, `SSDV_TGT`.`SNAPSHOT_DATE` AS `SNAPSHOT_DATE`
		, COALESCE(LEAD(`SSDV_TGT`.`SNAPSHOT_DATE`)OVER(PARTITION BY `HUB_SRC`.`PATIENT_HKEY` ORDER BY `SSDV_TGT`.`SNAPSHOT_DATE`)
			, TO_TIMESTAMP('31/12/2999 23:59:59', 'dd/MM/yyyy HH:mm:ss')) AS `END_SNAPSHOT_DATE`
		, COALESCE(`SAT_TGT1`.`PATIENT_HKEY`,`UNSAT_TGT1`.`PATIENT_HKEY`) AS `SAT_PATIENT_HKEY_SAT_HLTH_PATIENT_PATIENT_GDPR`
		, COALESCE(`SAT_TGT2`.`PATIENT_HKEY`,`UNSAT_TGT2`.`PATIENT_HKEY`) AS `SAT_PATIENT_HKEY_SAT_HLTH_PATIENT_PATIENT_INFO`
		, COALESCE(`CSAT_TGT1`.`PATIENT_HKEY`,`CUNSAT_TGT1`.`PATIENT_HKEY`) AS `SAT_PATIENT_HKEY_CALC_SAT_HLTH_PATIENT_PATIENT_GDPR`
		, COALESCE(`CSAT_TGT2`.`PATIENT_HKEY`,`CUNSAT_TGT2`.`PATIENT_HKEY`) AS `SAT_PATIENT_HKEY_CALC_SAT_HLTH_PATIENT_PATIENT_INFO`
		, COALESCE(`SAT_TGT1`.`LOAD_DATE`,`UNSAT_TGT1`.`LOAD_DATE`) AS `LOAD_DATE_SAT_HLTH_PATIENT_PATIENT_GDPR`
		, COALESCE(`SAT_TGT2`.`LOAD_DATE`,`UNSAT_TGT2`.`LOAD_DATE`) AS `LOAD_DATE_SAT_HLTH_PATIENT_PATIENT_INFO`
		, COALESCE(`CSAT_TGT1`.`LOAD_DATE`,`CUNSAT_TGT1`.`LOAD_DATE`) AS `LOAD_DATE_CALC_SAT_HLTH_PATIENT_PATIENT_GDPR`
		, COALESCE(`CSAT_TGT2`.`LOAD_DATE`,`CUNSAT_TGT2`.`LOAD_DATE`) AS `LOAD_DATE_CALC_SAT_HLTH_PATIENT_PATIENT_INFO`
	FROM `HEALTHCARE_FL`.`HUB_PATIENT` `HUB_SRC`
	INNER JOIN 	( 
		SELECT 
		DISTINCT 
			  `SAT_SRC1`.`PATIENT_HKEY` AS `HUB_HKEY`
			, `SAT_SRC1`.`LOAD_DATE` AS `SNAPSHOT_DATE`
		FROM `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_GDPR` `SAT_SRC1`
		UNION 
		SELECT 
		DISTINCT 
			  `CSAT_SRC1`.`PATIENT_HKEY` AS `HUB_HKEY`
			, `CSAT_SRC1`.`LOAD_DATE` AS `SNAPSHOT_DATE`
		FROM `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_GDPR_CALC` `CSAT_SRC1`
		UNION 
		SELECT 
		DISTINCT 
			  `SAT_SRC2`.`PATIENT_HKEY` AS `HUB_HKEY`
			, `SAT_SRC2`.`LOAD_DATE` AS `SNAPSHOT_DATE`
		FROM `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_INFO` `SAT_SRC2`
		UNION 
		SELECT 
		DISTINCT 
			  `CSAT_SRC2`.`PATIENT_HKEY` AS `HUB_HKEY`
			, `CSAT_SRC2`.`LOAD_DATE` AS `SNAPSHOT_DATE`
		FROM `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_INFO_CALC` `CSAT_SRC2`
	)  `SSDV_TGT` ON  `SSDV_TGT`.`HUB_HKEY` = `HUB_SRC`.`PATIENT_HKEY`
	LEFT OUTER JOIN 	( 
		SELECT 
			  `PIT_TGT`.`PATIENT_HKEY` AS `PATIENT_HKEY`
			, `PIT_TGT`.`SNAPSHOT_DATE` AS `SNAPSHOT_DATE`
		FROM `HEALTHCARE_BV`.`CPIT_PATIENT` `PIT_TGT`
	)  `PIT_CHECK` ON  `PIT_CHECK`.`PATIENT_HKEY` = `HUB_SRC`.`PATIENT_HKEY` AND `SSDV_TGT`.`SNAPSHOT_DATE` = `PIT_CHECK`.`SNAPSHOT_DATE`
	LEFT OUTER JOIN 	( 
		SELECT 
			  `SAT_SRC1`.`PATIENT_HKEY` AS `PATIENT_HKEY`
			, `SAT_SRC1`.`LOAD_DATE` AS `LOAD_DATE`
			, COALESCE(LEAD(`SAT_SRC1`.`LOAD_DATE`)OVER(PARTITION BY `SAT_SRC1`.`PATIENT_HKEY` ORDER BY `SAT_SRC1`.`LOAD_DATE`)
				, TO_TIMESTAMP('31/12/2999 23:59:59', 'dd/MM/yyyy HH:mm:ss')) AS `ENDING_LOAD_TIMESTAMP`
		FROM `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_GDPR` `SAT_SRC1`
	)  `SAT_TGT1` ON  `HUB_SRC`.`PATIENT_HKEY` = `SAT_TGT1`.`PATIENT_HKEY` AND `SSDV_TGT`.`SNAPSHOT_DATE` >= `SAT_TGT1`.`LOAD_DATE` AND 
		`SSDV_TGT`.`SNAPSHOT_DATE` < `SAT_TGT1`.`ENDING_LOAD_TIMESTAMP`
	LEFT OUTER JOIN 	( 
		SELECT 
			  `SAT_SRC2`.`PATIENT_HKEY` AS `PATIENT_HKEY`
			, `SAT_SRC2`.`LOAD_DATE` AS `LOAD_DATE`
			, COALESCE(LEAD(`SAT_SRC2`.`LOAD_DATE`)OVER(PARTITION BY `SAT_SRC2`.`PATIENT_HKEY` ORDER BY `SAT_SRC2`.`LOAD_DATE`)
				, TO_TIMESTAMP('31/12/2999 23:59:59', 'dd/MM/yyyy HH:mm:ss')) AS `ENDING_LOAD_TIMESTAMP`
		FROM `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_INFO` `SAT_SRC2`
	)  `SAT_TGT2` ON  `HUB_SRC`.`PATIENT_HKEY` = `SAT_TGT2`.`PATIENT_HKEY` AND `SSDV_TGT`.`SNAPSHOT_DATE` >= `SAT_TGT2`.`LOAD_DATE` AND 
		`SSDV_TGT`.`SNAPSHOT_DATE` < `SAT_TGT2`.`ENDING_LOAD_TIMESTAMP`
	LEFT OUTER JOIN 	( 
		SELECT 
			  `CSAT_SRC1`.`PATIENT_HKEY` AS `PATIENT_HKEY`
			, `CSAT_SRC1`.`LOAD_DATE` AS `LOAD_DATE`
			, COALESCE(LEAD(`CSAT_SRC1`.`LOAD_DATE`)OVER(PARTITION BY `CSAT_SRC1`.`PATIENT_HKEY` ORDER BY `CSAT_SRC1`.`LOAD_DATE`)
				, TO_TIMESTAMP('31/12/2999 23:59:59', 'dd/MM/yyyy HH:mm:ss')) AS `ENDING_LOAD_TIMESTAMP`
		FROM `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_GDPR_CALC` `CSAT_SRC1`
	)  `CSAT_TGT1` ON  `HUB_SRC`.`PATIENT_HKEY` = `CSAT_TGT1`.`PATIENT_HKEY` AND `SSDV_TGT`.`SNAPSHOT_DATE` >= `CSAT_TGT1`.`LOAD_DATE` AND 
		`SSDV_TGT`.`SNAPSHOT_DATE` < `CSAT_TGT1`.`ENDING_LOAD_TIMESTAMP`
	LEFT OUTER JOIN 	( 
		SELECT 
			  `CSAT_SRC2`.`PATIENT_HKEY` AS `PATIENT_HKEY`
			, `CSAT_SRC2`.`LOAD_DATE` AS `LOAD_DATE`
			, COALESCE(LEAD(`CSAT_SRC2`.`LOAD_DATE`)OVER(PARTITION BY `CSAT_SRC2`.`PATIENT_HKEY` ORDER BY `CSAT_SRC2`.`LOAD_DATE`)
				, TO_TIMESTAMP('31/12/2999 23:59:59', 'dd/MM/yyyy HH:mm:ss')) AS `ENDING_LOAD_TIMESTAMP`
		FROM `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_INFO_CALC` `CSAT_SRC2`
	)  `CSAT_TGT2` ON  `HUB_SRC`.`PATIENT_HKEY` = `CSAT_TGT2`.`PATIENT_HKEY` AND `SSDV_TGT`.`SNAPSHOT_DATE` >= `CSAT_TGT2`.`LOAD_DATE` AND 
		`SSDV_TGT`.`SNAPSHOT_DATE` < `CSAT_TGT2`.`ENDING_LOAD_TIMESTAMP`
	INNER JOIN `HEALTHCARE_MTD`.`MTD_EXCEPTION_RECORDS` `MEX_SRC` ON  `MEX_SRC`.`RECORD_TYPE` = 'U'
	INNER JOIN `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_GDPR` `UNSAT_TGT1` ON  CAST(`MEX_SRC`.`LOAD_CYCLE_ID` AS INTEGER) = `UNSAT_TGT1`.`LOAD_CYCLE_ID`
	INNER JOIN `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_INFO` `UNSAT_TGT2` ON  CAST(`MEX_SRC`.`LOAD_CYCLE_ID` AS INTEGER) = `UNSAT_TGT2`.`LOAD_CYCLE_ID`
	INNER JOIN `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_GDPR_CALC` `CUNSAT_TGT1` ON  CAST(`MEX_SRC`.`LOAD_CYCLE_ID` AS INTEGER) = `CUNSAT_TGT1`.`LOAD_CYCLE_ID`
	INNER JOIN `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_INFO_CALC` `CUNSAT_TGT2` ON  CAST(`MEX_SRC`.`LOAD_CYCLE_ID` AS INTEGER) = `CUNSAT_TGT2`.`LOAD_CYCLE_ID`
	WHERE  `PIT_CHECK`.`PATIENT_HKEY` is null
	;
