CREATE  VIEW "DATA_WAREHOUSE"."DIM_CUSTOMERS"  AS 
	WITH "DVO_BASE" AS 
	( 
		SELECT 
			  "HUB_SRC"."CUSTOMERS_HKEY" AS "BASE_OBJECT_H_KEY"
			, "HUB_SRC"."PERSON_ID_BK" AS "PERSON_ID_BK"
			, "PIT_SRC1"."SNAPSHOT_TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "SAT_SRC1_1"."FIRST_PURCHASE" AS "FIRST_PURCHASE_SAT_SLS_CUSTOMERS_GDPR"
			, "SAT_SRC1_1"."GENDER" AS "GENDER"
			, "SAT_SRC1_1"."BIRTHDATE" AS "BIRTHDATE"
			, "SAT_SRC1_1"."LASTNAME" AS "LASTNAME"
			, "SAT_SRC1_1"."FIRSTNAME" AS "FIRSTNAME"
			, "SAT_SRC1_1"."PERSON_NUMBER" AS "PERSON_NUMBER_SAT_SLS_CUSTOMERS_GDPR"
			, "SAT_SRC1_2"."SEND_COMMERCIAL_MESSAGES" AS "SEND_COMMERCIAL_MESSAGES"
			, "SAT_SRC1_3"."CUSTOMER_MEMBER_CARD_NO" AS "CUSTOMER_MEMBER_CARD_NO"
			, "SAT_SRC1_3"."PERSON_ID" AS "PERSON_ID"
			, UPPER(SHA1_HEX(  UPPER(REPLACE(COALESCE(TRIM( "HUB_SRC"."CUSTOMERS_HKEY"),'~'),'\#','\\' || '\#'))|| '\#'  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC1_1"."FIRST_PURCHASE",
				 'DD/MM/YYYY')),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_1"."GENDER"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC1_1"."BIRTHDATE", 'DD/MM/YYYY')),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_1"."LASTNAME"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_1"."FIRSTNAME"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC1_1"."PERSON_NUMBER")),'~'),'\#','\\' || '\#'))|| '\#' || UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC1_2"."FIRST_PURCHASE", 'DD/MM/YYYY')),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC1_2"."SEND_COMMERCIAL_MESSAGES")),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC1_2"."PERSON_NUMBER")),'~'),'\#','\\' || '\#'))|| '\#' || UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_3"."CUSTOMER_MEMBER_CARD_NO"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_3"."PERSON_ID"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_3"."PERSON_ID"),'~'),'\#','\\' || '\#'))|| '\#'              )) AS "DIM_HASH_DIFF"
		FROM "VS_DEMO_DV_SNW_FL"."HUB_CUSTOMERS" "HUB_SRC"
		INNER JOIN "VS_DEMO_DV_SNW_BV"."PIT_DETAIL_TRANS_CUSTOMERS" "PIT_SRC1" ON  "HUB_SRC"."CUSTOMERS_HKEY" = "PIT_SRC1"."CUSTOMERS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_CUSTOMERS_GDPR" "SAT_SRC1_1" ON  "PIT_SRC1"."SAT_SLS_CUSTOMERS_GDPR_HKEY" = "SAT_SRC1_1"."CUSTOMERS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_CUSTOMERS_GENERAL" "SAT_SRC1_2" ON  "PIT_SRC1"."SAT_SLS_CUSTOMERS_GENERAL_HKEY" = "SAT_SRC1_2"."CUSTOMERS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_VST_CUSTOMERS" "SAT_SRC1_3" ON  "PIT_SRC1"."SAT_VST_CUSTOMERS_HKEY" = "SAT_SRC1_3"."CUSTOMERS_HKEY"
	)
	, "HASH_DIFF_DATA_SET" AS 
	( 
		SELECT 
			  "DVO_BASE"."BASE_OBJECT_H_KEY" AS "BASE_OBJECT_H_KEY"
			, "DVO_BASE"."PERSON_ID_BK" AS "PERSON_ID_BK"
			, "DVO_BASE"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "DVO_BASE"."FIRST_PURCHASE_SAT_SLS_CUSTOMERS_GDPR" AS "FIRST_PURCHASE_SAT_SLS_CUSTOMERS_GDPR"
			, "DVO_BASE"."GENDER" AS "GENDER"
			, "DVO_BASE"."BIRTHDATE" AS "BIRTHDATE"
			, "DVO_BASE"."LASTNAME" AS "LASTNAME"
			, "DVO_BASE"."FIRSTNAME" AS "FIRSTNAME"
			, "DVO_BASE"."PERSON_NUMBER_SAT_SLS_CUSTOMERS_GDPR" AS "PERSON_NUMBER_SAT_SLS_CUSTOMERS_GDPR"
			, "DVO_BASE"."SEND_COMMERCIAL_MESSAGES" AS "SEND_COMMERCIAL_MESSAGES"
			, "DVO_BASE"."CUSTOMER_MEMBER_CARD_NO" AS "CUSTOMER_MEMBER_CARD_NO"
			, "DVO_BASE"."PERSON_ID" AS "PERSON_ID"
			, CASE WHEN COALESCE(LEAD("DVO_BASE"."DIM_HASH_DIFF")OVER(PARTITION BY "DVO_BASE"."BASE_OBJECT_H_KEY" ORDER BY "DVO_BASE"."SNAPSHOT__TIMESTAMP")
				,'XXX')!= "DVO_BASE"."DIM_HASH_DIFF" THEN 1 ELSE 0 END AS "CHANGE_FLAG"
		FROM "DVO_BASE" "DVO_BASE"
	)
	, "FILTERED_DATA_SET" AS 
	( 
		SELECT 
			  "HASH_DIFF_DATA_SET"."BASE_OBJECT_H_KEY" AS "BASE_OBJECT_H_KEY"
			, "HASH_DIFF_DATA_SET"."PERSON_ID_BK" AS "PERSON_ID_BK"
			, "HASH_DIFF_DATA_SET"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "HASH_DIFF_DATA_SET"."FIRST_PURCHASE_SAT_SLS_CUSTOMERS_GDPR" AS "FIRST_PURCHASE_SAT_SLS_CUSTOMERS_GDPR"
			, "HASH_DIFF_DATA_SET"."GENDER" AS "GENDER"
			, "HASH_DIFF_DATA_SET"."BIRTHDATE" AS "BIRTHDATE"
			, "HASH_DIFF_DATA_SET"."LASTNAME" AS "LASTNAME"
			, "HASH_DIFF_DATA_SET"."FIRSTNAME" AS "FIRSTNAME"
			, "HASH_DIFF_DATA_SET"."PERSON_NUMBER_SAT_SLS_CUSTOMERS_GDPR" AS "PERSON_NUMBER_SAT_SLS_CUSTOMERS_GDPR"
			, "HASH_DIFF_DATA_SET"."SEND_COMMERCIAL_MESSAGES" AS "SEND_COMMERCIAL_MESSAGES"
			, "HASH_DIFF_DATA_SET"."CUSTOMER_MEMBER_CARD_NO" AS "CUSTOMER_MEMBER_CARD_NO"
			, "HASH_DIFF_DATA_SET"."PERSON_ID" AS "PERSON_ID"
		FROM "HASH_DIFF_DATA_SET" "HASH_DIFF_DATA_SET"
		WHERE  "HASH_DIFF_DATA_SET"."CHANGE_FLAG" = 1
	)
	SELECT 
		  UPPER(SHA1_HEX(  UPPER(REPLACE(COALESCE(TRIM( "FILTERED_DATA_SET"."PERSON_ID_BK"),'~'),'\#','\\' || '\#'))|| 
			'\#' || UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP", 'DD/MM/YYYY HH24:MI:SS')),'~'),'\#','\\' || '\#'))|| '\#'  )) AS "DIM_CUSTOMERS_HKEY"
		, "FILTERED_DATA_SET"."BASE_OBJECT_H_KEY" AS "CUSTOMERS_HKEY"
		, "FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
		, COALESCE(LEAD("FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP")OVER(PARTITION BY "FILTERED_DATA_SET"."BASE_OBJECT_H_KEY" ORDER BY "FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP")
			, TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')) AS "END_SNAPSHOT__TIMESTAMP"
		, "FILTERED_DATA_SET"."FIRST_PURCHASE_SAT_SLS_CUSTOMERS_GDPR" AS "FIRST_PURCHASE_SAT_SLS_CUSTOMERS_GDPR"
		, "FILTERED_DATA_SET"."GENDER" AS "GENDER"
		, "FILTERED_DATA_SET"."BIRTHDATE" AS "BIRTHDATE"
		, "FILTERED_DATA_SET"."LASTNAME" AS "LASTNAME"
		, "FILTERED_DATA_SET"."FIRSTNAME" AS "FIRSTNAME"
		, "FILTERED_DATA_SET"."PERSON_NUMBER_SAT_SLS_CUSTOMERS_GDPR" AS "PERSON_NUMBER_SAT_SLS_CUSTOMERS_GDPR"
		, "FILTERED_DATA_SET"."SEND_COMMERCIAL_MESSAGES" AS "SEND_COMMERCIAL_MESSAGES"
		, "FILTERED_DATA_SET"."CUSTOMER_MEMBER_CARD_NO" AS "CUSTOMER_MEMBER_CARD_NO"
		, "FILTERED_DATA_SET"."PERSON_ID" AS "PERSON_ID"
	FROM "FILTERED_DATA_SET" "FILTERED_DATA_SET"
	;

 
 