
DROP VIEW IF EXISTS "INFORMATION_MARTS"."DIM_PRODUCTS";
CREATE  VIEW "INFORMATION_MARTS"."DIM_PRODUCTS"  AS 
	WITH "DVO_BASE" AS 
	( 
		SELECT 
			  "HUB_SRC"."PRODUCTS_HKEY" AS "BASE_OBJECT_H_KEY"
			, "HUB_SRC"."PRODUCTS_BK" AS "PRODUCTS_BK"
			, "PIT_SRC1"."SNAPSHOT_TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "SAT_SRC1_3"."ENGINE_TYPE" AS "ENGINE_TYPE"
			, "SAT_SRC1_3"."CODE" AS "CODE"
			, "SAT_SRC1_3"."SEATS" AS "SEATS"
			, "SAT_SRC1_4"."ENGINE_CC" AS "ENGINE_CC"
			, UPPER(SHA1_HEX(  UPPER(REPLACE(COALESCE(TRIM( "HUB_SRC"."PRODUCTS_HKEY"),'~'),'\#','\\' || '\#'))|| '\#'    || UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_3"."ENGINE_TYPE")
				,'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_3"."CODE"),'~'),'\#','\\' || '\#'))|| '\#' ||  UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("SAT_SRC1_3"."SEATS")),'~'),'\#','\\' || '\#'))|| '\#' || UPPER(REPLACE(COALESCE(TRIM( "SAT_SRC1_4"."ENGINE_CC"),'~'),'\#','\\' || '\#'))|| '\#'        )) AS "DIM_HASH_DIFF"
		FROM "VS_DEMO_DV_SNW_FL"."HUB_PRODUCTS" "HUB_SRC"
		INNER JOIN "VS_DEMO_DV_SNW_BV"."PIT_DETAIL_TRANS_PRODUCTS" "PIT_SRC1" ON  "HUB_SRC"."PRODUCTS_HKEY" = "PIT_SRC1"."PRODUCTS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_PRD_MOTORVEHICLES_PRODUCTS" "SAT_SRC1_1" ON  "PIT_SRC1"."SAT_PRD_MOTORVEHICLES_PRODUCTS_HKEY" = "SAT_SRC1_1"."PRODUCTS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_PRD_NONMOTORVEHICLES_PRODUCTS" "SAT_SRC1_2" ON  "PIT_SRC1"."SAT_PRD_NONMOTORVEHICLES_PRODUCTS_HKEY" = "SAT_SRC1_2"."PRODUCTS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_PASSENGERCAR_PRODUCTS" "SAT_SRC1_3" ON  "PIT_SRC1"."SAT_SLS_PASSENGERCAR_PRODUCTS_HKEY" = "SAT_SRC1_3"."PRODUCTS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_PASSENGER_CAR_ENGINE" "SAT_SRC1_4" ON  "PIT_SRC1"."SAT_SLS_PASSENGER_CAR_ENGINE_HKEY" = "SAT_SRC1_4"."PRODUCTS_HKEY" 
					AND "SAT_SRC1_4"."ENGINE_TYPE_SEQ" = 'E'
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_BICYCLES_PRODUCTS" "SAT_SRC1_5" ON  "PIT_SRC1"."SAT_SLS_BICYCLES_PRODUCTS_HKEY" = "SAT_SRC1_5"."PRODUCTS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_ELECTRICBICYCLES_PRODUCTS" "SAT_SRC1_6" ON  "PIT_SRC1"."SAT_SLS_ELECTRICBICYCLES_PRODUCTS_HKEY" = "SAT_SRC1_6"."PRODUCTS_HKEY"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_MOTORCYCLES_PRODUCTS" "SAT_SRC1_7" ON  "PIT_SRC1"."SAT_SLS_MOTORCYCLES_PRODUCTS_HKEY" = "SAT_SRC1_7"."PRODUCTS_HKEY"
	)
	, "HASH_DIFF_DATA_SET" AS 
	( 
		SELECT 
			  "DVO_BASE"."BASE_OBJECT_H_KEY" AS "BASE_OBJECT_H_KEY"
			, "DVO_BASE"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "DVO_BASE"."ENGINE_TYPE" AS "ENGINE_TYPE"
			, "DVO_BASE"."CODE" AS "CODE"
			, "DVO_BASE"."SEATS" AS "SEATS"
			, "DVO_BASE"."ENGINE_CC" AS "ENGINE_CC"
			, CASE WHEN COALESCE(LEAD("DVO_BASE"."DIM_HASH_DIFF")OVER(PARTITION BY "DVO_BASE"."BASE_OBJECT_H_KEY" ORDER BY "DVO_BASE"."SNAPSHOT__TIMESTAMP")
				,'XXX')!= "DVO_BASE"."DIM_HASH_DIFF" THEN 1 ELSE 0 END AS "CHANGE_FLAG"
		FROM "DVO_BASE" "DVO_BASE"
	)
	, "FILTERED_DATA_SET" AS 
	( 
		SELECT 
			  "HASH_DIFF_DATA_SET"."BASE_OBJECT_H_KEY" AS "BASE_OBJECT_H_KEY"
			, "HASH_DIFF_DATA_SET"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
			, "HASH_DIFF_DATA_SET"."ENGINE_TYPE" AS "ENGINE_TYPE"
			, "HASH_DIFF_DATA_SET"."CODE" AS "CODE"
			, "HASH_DIFF_DATA_SET"."SEATS" AS "SEATS"
			, "HASH_DIFF_DATA_SET"."ENGINE_CC" AS "ENGINE_CC"
		FROM "HASH_DIFF_DATA_SET" "HASH_DIFF_DATA_SET"
		WHERE  "HASH_DIFF_DATA_SET"."CHANGE_FLAG" = 1
	)
	SELECT 
		  UPPER(SHA1_HEX(  || UPPER(REPLACE(COALESCE(TRIM( TO_CHAR("FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP", 
			'DD/MM/YYYY HH24:MI:SS')),'~'),'\#','\\' || '\#'))|| '\#'  )) AS "DIM_PRODUCTS_HKEY"
		, "FILTERED_DATA_SET"."BASE_OBJECT_H_KEY" AS "PRODUCTS_HKEY"
		, "FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP" AS "SNAPSHOT__TIMESTAMP"
		, COALESCE(LEAD("FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP")OVER(PARTITION BY "FILTERED_DATA_SET"."BASE_OBJECT_H_KEY" ORDER BY "FILTERED_DATA_SET"."SNAPSHOT__TIMESTAMP")
			, TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')) AS "END_SNAPSHOT__TIMESTAMP"
		, "FILTERED_DATA_SET"."ENGINE_TYPE" AS "ENGINE_TYPE"
		, "FILTERED_DATA_SET"."CODE" AS "CODE"
		, "FILTERED_DATA_SET"."SEATS" AS "SEATS"
		, "FILTERED_DATA_SET"."ENGINE_CC" AS "ENGINE_CC"
	FROM "FILTERED_DATA_SET" "FILTERED_DATA_SET"
	;

 
 