CREATE  VIEW "BUSINESS_VAULT"."TEST_AGENTS_EFF"  AS 
	SELECT 
		  "SAT_SRC"."AGENTS_HKEY" AS "AGENTS_HKEY"
		, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "SAT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "SAT_SRC"."AGENTID" AS "AGENTID"
		, "SAT_SRC"."NAME" AS "NAME"
		, "SAT_SRC"."EMAIL" AS "EMAIL"
		, "SAT_SRC"."PHONE" AS "PHONE"
		, "SAT_SRC"."HIREDATE" AS "HIREDATE"
	FROM "TEST_FL"."SAT_TEST_AGENTS" "SAT_SRC"
	WHERE  "SAT_SRC"."LOAD_END_DATE" = TO_TIMESTAMP_NTZ('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS') and "SAT_SRC"."DELETE_FLAG" = CAST('N'  AS null)
	;