	WITH "MIV" AS 
	( 
		SELECT 
			  DATE_TRUNC('DAY',"LDS_SRC"."LOAD_DATE") AS "TRANSACTION_DAY"
			, "LND_SRC"."PRODUCTS_HKEY" AS "DIM_PRODUCTS_HKEY"
			, "LND_SRC"."SHOPS_HKEY" AS "DIM_SHOPS_HKEY"
			, "LND_SRC"."CUSTOMERS_HKEY" AS "DIM_CUSTOMERS_HKEY"
			, "LDS_SRC"."SHOP_ID" AS "SHOP_ID"
		FROM "VS_DEMO_DV_SNW_FL"."LND_PURCHASED_PRODUCT" "LND_SRC"
		INNER JOIN "VS_DEMO_DV_SNW_FL"."LDS_SLS_PURCHASED_PRODUCT_PURCHASEDBICYCLE" "LDS_SRC" ON  "LDS_SRC"."LND_PURCHASED_PRODUCT_HKEY" = "LND_SRC"."LND_PURCHASED_PRODUCT_HKEY"
	)
	SELECT 
		  "MIV"."TRANSACTION_DAY" AS "TRANSACTION_DAY"
		, UPPER(SHA1_HEX(UPPER(REPLACE(COALESCE(TRIM( "MIV"."DIM_PRODUCTS_HKEY"),'~'),'\#','\\' || '\#'))|| '\#' || UPPER(REPLACE(COALESCE(TRIM( DATE_TRUNC('DAY',
			"MIV"."TRANSACTION_DAY")),'~'),'\#','\\' || '\#'))|| '\#' )) AS "DIM_PRODUCTS_HKEY"
		, UPPER(SHA1_HEX(UPPER(REPLACE(COALESCE(TRIM( "MIV"."DIM_SHOPS_HKEY"),'~'),'\#','\\' || '\#'))|| '\#' || UPPER(REPLACE(COALESCE(TRIM( DATE_TRUNC('DAY',
			"MIV"."TRANSACTION_DAY")),'~'),'\#','\\' || '\#'))|| '\#' )) AS "DIM_SHOPS_HKEY"
		, UPPER(SHA1_HEX(UPPER(REPLACE(COALESCE(TRIM( "MIV"."DIM_CUSTOMERS_HKEY"),'~'),'\#','\\' || '\#'))|| '\#' || UPPER(REPLACE(COALESCE(TRIM( DATE_TRUNC('DAY',
			"MIV"."TRANSACTION_DAY")),'~'),'\#','\\' || '\#'))|| '\#' )) AS "DIM_CUSTOMERS_HKEY"
		, "MIV"."SHOP_ID" AS "SHOP_ID"
	FROM "MIV" "MIV"
	;

 