


CREATE    TABLE `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_GDPR_CALC`
(
		 `PATIENT_HKEY` STRING
		,`LOAD_DATE` TIMESTAMP
		,`LOAD_CYCLE_ID` INTEGER
		,`HASH_DIFF` STRING
		,`DELETE_FLAG` STRING
		,`ID` STRING
		,`NUMBER_OF_YEARS_SINCE_BIRTHDATE` INTEGER
) 
;

	INSERT INTO `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_GDPR_CALC`(
		 `PATIENT_HKEY`
		,`LOAD_DATE`
		,`LOAD_CYCLE_ID`
		,`HASH_DIFF`
		,`DELETE_FLAG`
		,`ID`
		,`NUMBER_OF_YEARS_SINCE_BIRTHDATE`
	)
	SELECT 
		  `SAT_SRC`.`PATIENT_HKEY` AS `PATIENT_HKEY`
		, `SAT_SRC`.`LOAD_DATE` AS `LOAD_DATE`
		, `SAT_SRC`.`LOAD_CYCLE_ID` AS `LOAD_CYCLE_ID`
		, `SAT_SRC`.`HASH_DIFF` AS `HASH_DIFF`
		, `SAT_SRC`.`DELETE_FLAG` AS `DELETE_FLAG`
		, `SAT_SRC`.`ID` AS `ID`
		, DATEDIFF(year,`SAT_SRC`.`BIRTHDATE`,current_date()) AS `NUMBER_OF_YEARS_SINCE_BIRTHDATE`
	FROM `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_GDPR` `SAT_SRC`
	;


