
CREATE OR REPLACE VIEW `INFORMATION_MARTS`.`DIM_PATIENT`  AS 
	SELECT 
		  UPPER(sha1(  UPPER(REPLACE(COALESCE(TRIM( CAST(`FILTERED_DATA_SET`.`ID_BK` AS STRING)),'~'),'#','\\' || '#'))
			|| '#' || UPPER(REPLACE(COALESCE(TRIM( DATE_FORMAT(`FILTERED_DATA_SET`.`SNAPSHOT__TIMESTAMP`, 'dd/MM/yyyy HH:mm:ss')),'~'),'#','\\' || '#'))|| '#'  )) AS `DIM_PATIENT_HKEY`
		, `FILTERED_DATA_SET`.`BASE_OBJECT_H_KEY` AS `PATIENT_HKEY`
		, `FILTERED_DATA_SET`.`ID_BK` AS `ID_BK`
		, `FILTERED_DATA_SET`.`SNAPSHOT__TIMESTAMP` AS `SNAPSHOT__TIMESTAMP`
		, COALESCE(LEAD(`FILTERED_DATA_SET`.`SNAPSHOT__TIMESTAMP`)OVER(PARTITION BY `FILTERED_DATA_SET`.`BASE_OBJECT_H_KEY` ORDER BY `FILTERED_DATA_SET`.`SNAPSHOT__TIMESTAMP`)
			, TO_TIMESTAMP('31/12/2999 23:59:59' , 'dd/MM/yyyy HH:mm:ss')) AS `END_SNAPSHOT__TIMESTAMP`
		, `FILTERED_DATA_SET`.`RACE` AS `RACE`
		, `FILTERED_DATA_SET`.`MARITAL` AS `MARITAL`
		, `FILTERED_DATA_SET`.`SSN` AS `SSN`
		, `FILTERED_DATA_SET`.`BIRTHDATE` AS `BIRTHDATE`
		, `FILTERED_DATA_SET`.`HEALTHCARE_COVERAGE` AS `HEALTHCARE_COVERAGE`
		, `FILTERED_DATA_SET`.`STATE` AS `STATE`
		, `FILTERED_DATA_SET`.`BIRTHPLACE` AS `BIRTHPLACE`
		, `FILTERED_DATA_SET`.`NUMBER_OF_YEARS_SINCE_BIRTHDATE` AS `NUMBER_OF_YEARS_SINCE_BIRTHDATE`
		, `FILTERED_DATA_SET`.`NUMBER_OF_YEARS_SINCE_DEATHDATE` AS `NUMBER_OF_YEARS_SINCE_DEATHDATE`
	FROM 	( 
		SELECT 
			  `HASH_DIFF_DATA_SET`.`BASE_OBJECT_H_KEY` AS `BASE_OBJECT_H_KEY`
			, `HASH_DIFF_DATA_SET`.`ID_BK` AS `ID_BK`
			, `HASH_DIFF_DATA_SET`.`SNAPSHOT__TIMESTAMP` AS `SNAPSHOT__TIMESTAMP`
			, `HASH_DIFF_DATA_SET`.`RACE` AS `RACE`
			, `HASH_DIFF_DATA_SET`.`MARITAL` AS `MARITAL`
			, `HASH_DIFF_DATA_SET`.`SSN` AS `SSN`
			, `HASH_DIFF_DATA_SET`.`BIRTHDATE` AS `BIRTHDATE`
			, `HASH_DIFF_DATA_SET`.`HEALTHCARE_COVERAGE` AS `HEALTHCARE_COVERAGE`
			, `HASH_DIFF_DATA_SET`.`STATE` AS `STATE`
			, `HASH_DIFF_DATA_SET`.`BIRTHPLACE` AS `BIRTHPLACE`
			, `HASH_DIFF_DATA_SET`.`NUMBER_OF_YEARS_SINCE_BIRTHDATE` AS `NUMBER_OF_YEARS_SINCE_BIRTHDATE`
			, `HASH_DIFF_DATA_SET`.`NUMBER_OF_YEARS_SINCE_DEATHDATE` AS `NUMBER_OF_YEARS_SINCE_DEATHDATE`
		FROM 	( 
			SELECT 
				  `DVO_BASE`.`BASE_OBJECT_H_KEY` AS `BASE_OBJECT_H_KEY`
				, `DVO_BASE`.`ID_BK` AS `ID_BK`
				, `DVO_BASE`.`SNAPSHOT__TIMESTAMP` AS `SNAPSHOT__TIMESTAMP`
				, `DVO_BASE`.`RACE` AS `RACE`
				, `DVO_BASE`.`MARITAL` AS `MARITAL`
				, `DVO_BASE`.`SSN` AS `SSN`
				, `DVO_BASE`.`BIRTHDATE` AS `BIRTHDATE`
				, `DVO_BASE`.`HEALTHCARE_COVERAGE` AS `HEALTHCARE_COVERAGE`
				, `DVO_BASE`.`STATE` AS `STATE`
				, `DVO_BASE`.`BIRTHPLACE` AS `BIRTHPLACE`
				, `DVO_BASE`.`NUMBER_OF_YEARS_SINCE_BIRTHDATE` AS `NUMBER_OF_YEARS_SINCE_BIRTHDATE`
				, `DVO_BASE`.`NUMBER_OF_YEARS_SINCE_DEATHDATE` AS `NUMBER_OF_YEARS_SINCE_DEATHDATE`
				, CASE WHEN COALESCE(LEAD(`DVO_BASE`.`DIM_HASH_DIFF`)OVER(PARTITION BY `DVO_BASE`.`BASE_OBJECT_H_KEY` ORDER BY `DVO_BASE`.`SNAPSHOT__TIMESTAMP`)
					,'XXX')!= `DVO_BASE`.`DIM_HASH_DIFF` THEN 1 ELSE 0 END AS `CHANGE_FLAG`
			FROM 	( 
				SELECT 
					  `HUB_SRC`.`PATIENT_HKEY` AS `BASE_OBJECT_H_KEY`
					, `HUB_SRC`.`ID_BK` AS `ID_BK`
					, `PIT_SRC2`.`SNAPSHOT_DATE` AS `SNAPSHOT__TIMESTAMP`
					, `SAT_SRC2_1`.`RACE` AS `RACE`
					, `SAT_SRC2_1`.`MARITAL` AS `MARITAL`
					, `SAT_SRC2_1`.`SSN` AS `SSN`
					, `SAT_SRC2_1`.`BIRTHDATE` AS `BIRTHDATE`
					, `SAT_SRC2_2`.`HEALTHCARE_COVERAGE` AS `HEALTHCARE_COVERAGE`
					, `SAT_SRC2_2`.`STATE` AS `STATE`
					, `SAT_SRC2_2`.`BIRTHPLACE` AS `BIRTHPLACE`
					, `CSAT_SRC1`.`NUMBER_OF_YEARS_SINCE_BIRTHDATE` AS `NUMBER_OF_YEARS_SINCE_BIRTHDATE`
					, `CSAT_SRC2`.`NUMBER_OF_YEARS_SINCE_DEATHDATE` AS `NUMBER_OF_YEARS_SINCE_DEATHDATE`
					, UPPER(sha1(  UPPER(REPLACE(COALESCE(TRIM( CAST(`HUB_SRC`.`PATIENT_HKEY` AS STRING)),'~'),'#','\\' || '#'))|| 
					     '#'    || UPPER(REPLACE(COALESCE(TRIM( CAST(`SAT_SRC2_1`.`RACE` AS STRING)),'~'),'#','\\' || '#'))|| 
						 '#'    || UPPER(REPLACE(COALESCE(TRIM( CAST(`SAT_SRC2_1`.`MARITAL` AS STRING)),'~'),'#','\\' || '#'))|| 
						 '#'    || UPPER(REPLACE(COALESCE(TRIM( CAST(`SAT_SRC2_1`.`SSN` AS STRING)),'~'),'#','\\' || '#'))|| 
						 '#'    || UPPER(REPLACE(COALESCE(TRIM( DATE_FORMAT(`SAT_SRC2_1`.`BIRTHDATE`, 'dd/MM/yyyy')),'~'),'#','\\' || '#'))|| 
						 '#'    || UPPER(REPLACE(COALESCE(TRIM( CAST(`SAT_SRC2_2`.`HEALTHCARE_COVERAGE` AS STRING)),'~'),'#','\\' || '#'))|| 
						 '#'    || UPPER(REPLACE(COALESCE(TRIM( CAST(`SAT_SRC2_2`.`STATE` AS STRING)),'~'),'#','\\' || '#'))|| 
						 '#'    || UPPER(REPLACE(COALESCE(TRIM( CAST(`SAT_SRC2_2`.`BIRTHPLACE` AS STRING)),'~'),'#','\\' || '#'))|| 
						 '#'    || UPPER(REPLACE(COALESCE(TRIM( CAST(`CSAT_SRC1`.`NUMBER_OF_YEARS_SINCE_BIRTHDATE` AS STRING)),'~'),'#','\\' || '#'))|| 
						 '#'    || UPPER(REPLACE(COALESCE(TRIM( CAST(`CSAT_SRC2`.`NUMBER_OF_YEARS_SINCE_DEATHDATE` AS STRING)),'~'),'#','\\' || '#'))|| '#'
						 )) AS `DIM_HASH_DIFF`
				FROM `HEALTHCARE_FL`.`HUB_PATIENT` `HUB_SRC`
				INNER JOIN `HEALTHCARE_BV`.`CPIT_PATIENT` `PIT_SRC2` ON  `HUB_SRC`.`PATIENT_HKEY` = `PIT_SRC2`.`PATIENT_HKEY`
				INNER JOIN `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_GDPR` `SAT_SRC2_1` ON  `PIT_SRC2`.`SAT_PATIENT_HKEY_SAT_HLTH_PATIENT_PATIENT_GDPR` = `SAT_SRC2_1`.`PATIENT_HKEY`
				INNER JOIN `HEALTHCARE_FL`.`SAT_HLTH_PATIENT_PATIENT_INFO` `SAT_SRC2_2` ON  `PIT_SRC2`.`SAT_PATIENT_HKEY_SAT_HLTH_PATIENT_PATIENT_INFO` = `SAT_SRC2_2`.`PATIENT_HKEY`
				INNER JOIN `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_GDPR_CALC` `CSAT_SRC1` ON  `PIT_SRC2`.`SAT_PATIENT_HKEY_CALC_SAT_HLTH_PATIENT_PATIENT_GDPR` = `CSAT_SRC1`.`PATIENT_HKEY` AND `PIT_SRC2`.`LOAD_DATE_CALC_SAT_HLTH_PATIENT_PATIENT_GDPR` = `CSAT_SRC1`.`LOAD_DATE`
				INNER JOIN `HEALTHCARE_BV`.`SAT_HLTH_PATIENT_PATIENT_INFO_CALC` `CSAT_SRC2` ON  `PIT_SRC2`.`SAT_PATIENT_HKEY_CALC_SAT_HLTH_PATIENT_PATIENT_INFO` = `CSAT_SRC2`.`PATIENT_HKEY` AND `PIT_SRC2`.`LOAD_DATE_CALC_SAT_HLTH_PATIENT_PATIENT_INFO` = `CSAT_SRC2`.`LOAD_DATE`
	)  `DVO_BASE`
	)  `HASH_DIFF_DATA_SET`
		WHERE  `HASH_DIFF_DATA_SET`.`CHANGE_FLAG` = 1
	)  `FILTERED_DATA_SET`
	;
