
	WITH "DVO_BASE1" AS 
	( 
		SELECT 
			  "DVO_SRC1"."ADDRESSES_HKEY" AS "BASE_OBJECT_H_KEY"
			, "SCD2_DIM_HUB_SRC1"."DIM_ADDRESSES_HKEY" AS "DIM_ADDRESSES_HKEY"
			, "SCD2_DIM_HUB_SRC1"."SNAPSHOT__TIMESTAMP" AS "FILTER_SNAPSHOT_TIMESTAMP"
			, "SCD2_DIM_HUB_SRC1"."END_SNAPSHOT__TIMESTAMP" AS "FILTER_END_SNAPSHOT_TIMESTAMP"
		FROM "VS_DEMO_DV_SNW_FL"."HUB_ADDRESSES" "DVO_SRC1"
		INNER JOIN "DATA_WAREHOUSE"."DIM_ADDRESSES" "SCD2_DIM_HUB_SRC1" ON  "DVO_SRC1"."ADDRESSES_HKEY" = "SCD2_DIM_HUB_SRC1"."ADDRESSES_HKEY"
	)
	, "DVO_BASE3" AS 
	( 
		SELECT 
			  "DVO_SRC3"."CUSTOMERS_HKEY" AS "BASE_OBJECT_H_KEY"
			, "SCD2_DIM_HUB_SRC3"."DIM_CUSTOMERS_HKEY" AS "DIM_CUSTOMERS_HKEY"
			, "SCD2_DIM_HUB_SRC3"."SNAPSHOT__TIMESTAMP" AS "FILTER_SNAPSHOT_TIMESTAMP"
			, "SCD2_DIM_HUB_SRC3"."END_SNAPSHOT__TIMESTAMP" AS "FILTER_END_SNAPSHOT_TIMESTAMP"
		FROM "VS_DEMO_DV_SNW_FL"."HUB_CUSTOMERS" "DVO_SRC3"
		INNER JOIN "DATA_WAREHOUSE"."DIM_CUSTOMERS" "SCD2_DIM_HUB_SRC3" ON  "DVO_SRC3"."CUSTOMERS_HKEY" = "SCD2_DIM_HUB_SRC3"."CUSTOMERS_HKEY"
	)
	SELECT 
		  "DVO_BASE1"."DIM_ADDRESSES_HKEY" AS "DIM_ADDRESSES_HKEY"
		, "DVO_BASE3"."DIM_CUSTOMERS_HKEY" AS "DIM_CUSTOMERS_HKEY"
		, "FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."INVOICE_ID" AS "INVOICE_ID_SAT_SLS_INVOICES"
		, "FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."CUSTOMER_INVOICE_ID" AS "CUSTOMER_INVOICE_ID"
		, "FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."AMOUNT" AS "AMOUNT_SAT_SLS_INVOICES"
		, "FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."INVOICE_DATE" AS "INVOICE_DATE"
	FROM "VS_DEMO_DV_SNW_BV"."BRIDGE_INVOICE_CUSTOMER_ADDRESS" "BRIDGE"
	INNER JOIN "VS_DEMO_DV_SNW_FL"."SAT_SLS_INVOICES" "FACT_ON_BRIDGE_SCD2_SAT_SELECTION" ON  "FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."INVOICES_HKEY" = "BRIDGE"."INVOICES_HKEY"
	INNER JOIN "DVO_BASE1" "DVO_BASE1" ON  "DVO_BASE1"."BASE_OBJECT_H_KEY" = "BRIDGE"."ADDRESSES_HKEY" AND "FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."INVOICE_DATE" > "DVO_BASE1"."FILTER_SNAPSHOT_TIMESTAMP" AND 
		"FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."INVOICE_DATE" <= "DVO_BASE1"."FILTER_END_SNAPSHOT_TIMESTAMP"
	INNER JOIN "DVO_BASE3" "DVO_BASE3" ON  "DVO_BASE3"."BASE_OBJECT_H_KEY" = "BRIDGE"."CUSTOMERS_HKEY" AND "FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."INVOICE_DATE" > "DVO_BASE3"."FILTER_SNAPSHOT_TIMESTAMP" AND 
		"FACT_ON_BRIDGE_SCD2_SAT_SELECTION"."INVOICE_DATE" <= "DVO_BASE3"."FILTER_END_SNAPSHOT_TIMESTAMP"
	;

 